

export const HOMESCREEN_TYPES = {
  HOMESCREEN_QUOTES_GET_ALL_REQUEST: 'HOMESCREEN_QUOTES_GET_ALL_REQUEST',
  HOMESCREEN_QUOTES_GET_ALL_SUCCESS: 'HOMESCREEN_QUOTES_GET_ALL_SUCCESS',
  HOMESCREEN_QUOTES_GET_ALL_ERRORS: 'HOMESCREEN_QUOTES_GET_ALL_ERRORS',
};
